### ISSUE TITLE
[Randomemoji] - Refresh when popped 

### ISSUE THREAD

**Issue by Stonedestroyer** [Stonedestroyer/Stone-Cogs#2]
Randomemoji should refresh menu when emote list is popped.

**Comment by devil-cyber** [comment]
I would like to work on this can you assign this issue to me

**Comment by Stonedestroyer** [comment]
I have assigned it to you, feel free to ask if you have any questions.

**Comment by devil-cyber** [comment]
Ok , thanks

**Comment by Stonedestroyer** [comment]
If you still working on it let me know, but I'ma assume it's abandoned.
